In [1]:
import matplotlib.pyplot as plt

In [2]:
help(plt.hist)

Help on function hist in module matplotlib.pyplot:

hist(x, bins=None, range=None, density=None, weights=None, cumulative=False, bottom=None, histtype='bar', align='mid', orientation='vertical', rwidth=None, log=False, color=None, label=None, stacked=False, normed=None, hold=None, data=None, **kwargs)
    Plot a histogram.
    
    Compute and draw the histogram of *x*. The return value is a
    tuple (*n*, *bins*, *patches*) or ([*n0*, *n1*, ...], *bins*,
    [*patches0*, *patches1*,...]) if the input contains multiple
    data.
    
    Multiple data can be provided via *x* as a list of datasets
    of potentially different length ([*x0*, *x1*, ...]), or as
    a 2-D ndarray in which each column is a dataset.  Note that
    the ndarray form is transposed relative to the list form.
    
    Masked arrays are not supported at present.
    
    Parameters
    ----------
    x : (n,) array or sequence of (n,) arrays
        Input values, this takes either a single array or a sequence of


In [5]:
# dictionaries
world={"albania":20.8,"afghanistan":92,"algeria":39.1}
print(world)

{'albania': 20.8, 'afghanistan': 92, 'algeria': 39.1}


In [6]:
world["albania"]

20.8

In [7]:
# strings,int,float,boolean are immutable objects , while list is mutable object
world2={"True":1,"false":0}
print(world2)

{'True': 1, 'false': 0}


In [8]:
world2["True"]

1

In [9]:
print(world.keys())

dict_keys(['albania', 'afghanistan', 'algeria'])


In [10]:
world["sealand"]=0.000027

In [11]:
print(world.keys())

dict_keys(['albania', 'afghanistan', 'algeria', 'sealand'])


In [12]:
print(world)

{'albania': 20.8, 'afghanistan': 92, 'algeria': 39.1, 'sealand': 2.7e-05}


In [13]:
world["sealand"]=0.00038

In [14]:
print(world)

{'albania': 20.8, 'afghanistan': 92, 'algeria': 39.1, 'sealand': 0.00038}


In [15]:
"sealand" in world

True

In [16]:
del(world["sealand"])

In [17]:
print(world)

{'albania': 20.8, 'afghanistan': 92, 'algeria': 39.1}


In [23]:
# creating dictionary of dictionaries using curly brackets
europe = { 'spain': { 'capital':'madrid', 'population':46.77 },
           'france': { 'capital':'paris', 'population':66.03 },
           'germany': { 'capital':'berlin', 'population':80.62 },
           'norway': { 'capital':'oslo', 'population':5.084 } }

print(europe)


{'spain': {'capital': 'madrid', 'population': 46.77}, 'france': {'capital': 'paris', 'population': 66.03}, 'germany': {'capital': 'berlin', 'population': 80.62}, 'norway': {'capital': 'oslo', 'population': 5.084}}


In [24]:
#europe["france"]["capital"]
europe["france"]

{'capital': 'paris', 'population': 66.03}

In [25]:
# Create sub-dictionary data
data={'capital':'rome','population':59.83}

In [26]:
europe["italy"]=data

In [27]:
print(europe)

{'spain': {'capital': 'madrid', 'population': 46.77}, 'france': {'capital': 'paris', 'population': 66.03}, 'germany': {'capital': 'berlin', 'population': 80.62}, 'norway': {'capital': 'oslo', 'population': 5.084}, 'italy': {'capital': 'rome', 'population': 59.83}}


In [29]:
# creating a dataframe from dictionary , dictionary from lists
names = ['United States', 'Australia', 'Japan', 'India', 'Russia', 'Morocco', 'Egypt']
dr =  [True, False, False, False, True, True, True]
cpc = [809, 731, 588, 18, 200, 70, 45]

print(names)
print(dr)
print(cpc)

my_dict={'country':names,'drives_right':dr,'cars_per_cap':cpc} 

print(my_dict)
print(my_dict.keys())

import pandas as pd

brics=pd.DataFrame(my_dict)

['United States', 'Australia', 'Japan', 'India', 'Russia', 'Morocco', 'Egypt']
[True, False, False, False, True, True, True]
[809, 731, 588, 18, 200, 70, 45]
{'country': ['United States', 'Australia', 'Japan', 'India', 'Russia', 'Morocco', 'Egypt'], 'drives_right': [True, False, False, False, True, True, True], 'cars_per_cap': [809, 731, 588, 18, 200, 70, 45]}
dict_keys(['country', 'drives_right', 'cars_per_cap'])


In [30]:
print(brics)

         country  drives_right  cars_per_cap
0  United States          True           809
1      Australia         False           731
2          Japan         False           588
3          India         False            18
4         Russia          True           200
5        Morocco          True            70
6          Egypt          True            45


In [31]:
brics.index=["US","AU","JP","IN","RU","MR","EG"]

In [32]:
print(brics)

          country  drives_right  cars_per_cap
US  United States          True           809
AU      Australia         False           731
JP          Japan         False           588
IN          India         False            18
RU         Russia          True           200
MR        Morocco          True            70
EG          Egypt          True            45


In [36]:
print(brics["country"])
type(brics["country"])

US    United States
AU        Australia
JP            Japan
IN            India
RU           Russia
MR          Morocco
EG            Egypt
Name: country, dtype: object


pandas.core.series.Series

In [37]:
print(brics[["country"]])
type(brics[["country"]])

          country
US  United States
AU      Australia
JP          Japan
IN          India
RU         Russia
MR        Morocco
EG          Egypt


pandas.core.frame.DataFrame

In [38]:
brics[["country","cars_per_cap"]]

country  cars_per_cap
US  United States           809
AU      Australia           731
JP          Japan           588
IN          India            18
RU         Russia           200
MR        Morocco            70
EG          Egypt            45

In [39]:
brics[1:4]

country  drives_right  cars_per_cap
AU  Australia         False           731
JP      Japan         False           588
IN      India         False            18

In [40]:
# using loc and iloc

print(brics)

          country  drives_right  cars_per_cap
US  United States          True           809
AU      Australia         False           731
JP          Japan         False           588
IN          India         False            18
RU         Russia          True           200
MR        Morocco          True            70
EG          Egypt          True            45


In [30]:
brics.loc["RU"] ## tis comes out as series

country         Russia
drives_right      True
cars_per_cap       200
Name: RU, dtype: object

In [41]:
brics.loc[["RU"]] # preferred way

country  drives_right  cars_per_cap
RU  Russia          True           200

In [42]:
brics.loc[["RU","IN","JP"]]

country  drives_right  cars_per_cap
RU  Russia          True           200
IN   India         False            18
JP   Japan         False           588

In [43]:
brics.loc[["RU","IN","JP"],["country","drives_right"]]

country  drives_right
RU  Russia          True
IN   India         False
JP   Japan         False

In [44]:
brics.iloc[[4]]

country  drives_right  cars_per_cap
RU  Russia          True           200

In [45]:
brics.iloc[[2,3,4]]

country  drives_right  cars_per_cap
JP   Japan         False           588
IN   India         False            18
RU  Russia          True           200

In [46]:
brics.iloc[[2,3,4],[0,1]]

country  drives_right
JP   Japan         False
IN   India         False
RU  Russia          True

In [56]:
print(True==False)


False


In [57]:
print((-5*15)!=75)

True


In [58]:
print('pyscript'=='PyScript')

False


In [59]:
print(True==1)

True


In [60]:
# filtering pandas dataframe


In [61]:
fam=[1.32,1.32,5.3,4.5]

In [62]:
print(fam)


[1.32, 1.32, 5.3, 4.5]


In [63]:
for i in fam: ## lopping over the list single dimensional list
    print(i)

1.32
1.32
5.3
4.5


In [64]:
for ind,j in enumerate(fam):   ## for getting index use enumerate
    print(str(ind)  ,' ' + str(j))

0  1.32
1  1.32
2  5.3
3  4.5


In [65]:
name="sudhakar"
for c in name:
    print(c.capitalize())

S
U
D
H
A
K
A
R


In [67]:
# looping over dictionaries use items method

country={"india":'delhi',"pakistan":'islambad','srilanka':'colombo'}
print(country)
print(country.keys())
print(country['india'])


for ind,j in country.items():
    print(str(ind)+ '  capital is  '+ str(j))

{'india': 'delhi', 'pakistan': 'islambad', 'srilanka': 'colombo'}
dict_keys(['india', 'pakistan', 'srilanka'])
delhi
india  capital is  delhi
pakistan  capital is  islambad
srilanka  capital is  colombo


In [72]:
## looping ver numpy array use nditer method
import numpy as np
height=np.array([1.72,1.73,1.58,1.82])
weight=np.array([56,65,72,94])
bm=np.array([height,weight])
print(bm)

[[ 1.72  1.73  1.58  1.82]
 [56.   65.   72.   94.  ]]


In [69]:
for i in bm:
    print(i)

[1.72 1.73 1.58 1.82]
[56. 65. 72. 94.]


In [70]:
for i in np.nditer(bm):
    print(i)

1.72
1.73
1.58
1.82
56.0
65.0
72.0
94.0


In [73]:
np.random.seed(123)
np.random.rand()

0.6964691855978616

In [74]:
np.random.rand()

0.28613933495037946

In [75]:
np.random.seed(400)
np.random.rand()

0.6687289088341747

In [76]:
np.random.rand()

0.22599847009845475

In [77]:
np.random.rand()

0.8592987413441139

In [78]:
np.random.seed(123)
np.random.rand()
np.random.rand()

0.28613933495037946