In [1]:
# example for python list- coems with square brackets and can any datatype 
sudhakar=["dhivya",27,"vd",2,"sud",30,"mom",55,"dad",62,"bro",25]

In [2]:
print(sudhakar)

['dhivya', 27, 'vd', 2, 'sud', 30, 'mom', 55, 'dad', 62, 'bro', 25]


In [3]:
print(type(sudhakar))

<class 'list'>


In [4]:
sudhakar[2:4]


['vd', 2]

In [5]:
sudhakar[-4:-1]

['dad', 62, 'bro']

In [6]:
sudhakar[:6]

['dhivya', 27, 'vd', 2, 'sud', 30]

In [9]:
sudhakar[:-5]

['dhivya', 27, 'vd', 2, 'sud', 30, 'mom']

In [10]:
del(sudhakar[2])

In [11]:
sudhakar

['dhivya', 27, 2, 'sud', 30, 'mom', 55, 'dad', 62, 'bro', 25]

In [12]:
sudhakar[0:3]=["sh",50,45]

In [13]:
sudhakar

['sh', 50, 45, 'sud', 30, 'mom', 55, 'dad', 62, 'bro', 25]

In [14]:
sudhakar+['Fil',58]

['sh', 50, 45, 'sud', 30, 'mom', 55, 'dad', 62, 'bro', 25, 'Fil', 58]

In [15]:
help(max)

Help on built-in function max in module builtins:

max(...)
    max(iterable, *[, default=obj, key=func]) -> value
    max(arg1, arg2, *args, *[, key=func]) -> value
    
    With a single iterable argument, return its biggest item. The
    default keyword-only argument specifies an object to return if
    the provided iterable is empty.
    With two or more arguments, return the largest argument.



In [16]:
help(round)

Help on built-in function round in module builtins:

round(...)
    round(number[, ndigits]) -> number
    
    Round a number to a given precision in decimal digits (default 0 digits).
    This returns an int when called with one argument, otherwise the
    same type as the number. ndigits may be negative.



In [17]:
round(1.7888545,1)

1.8

In [22]:
round(1.777)

2

In [23]:
height=1.73

In [24]:
height.conjugate()

1.73

In [25]:
height=[12,13,14]
weight=[62,60,13]


In [26]:
bmi=height/weight**2

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [31]:
## list cannot manipulate-here numpy array helps- array in python needs to be written with([])
import numpy as np
h=np.array([12,13,14])


In [32]:
w=np.array([2,4,5])
bmi=h/w**2

In [33]:
print(bmi)


[3.     0.8125 0.56  ]


In [34]:
height=[12,13,14]
height_2d=height+height
print(height_2d)

[12, 13, 14, 12, 13, 14]


In [34]:
h1=np.array(height)
h2=h1+h1
print(type(h1))
print(h2)

<class 'numpy.ndarray'>
[24 26 28]


In [39]:
h2<25

array([ True, False, False])

In [41]:
h3=h2[h2<25]
print(type(h3))
print(h3)

<class 'numpy.ndarray'>
[24]


In [48]:


np_1d=np.array([1,2,3])
np_2d=np.array([[1,2,2,3],[2,4,5,6]])

In [50]:
print(np_1d.shape)
print(np_2d.shape)

(3,)
(2, 4)


In [51]:
print(np_2d)

[[1 2 2 3]
 [2 4 5 6]]


In [54]:
np_2d[0]

array([1, 2, 2, 3])

In [55]:
np_2d[0][2]

2

In [56]:
np_2d[0,3]

3

In [57]:
np_2d[1,3]

6

In [59]:
np_3d=np.array([[1,2,3,4],[5,6,7,8],[3,4,5,8]])

In [60]:
print(np_3d)

[[1 2 3 4]
 [5 6 7 8]
 [3 4 5 8]]


In [62]:
print(np_3d.shape)

(3, 4)


In [63]:
np_3d[:,1:3]

array([[2, 3],
       [6, 7],
       [4, 5]])

In [67]:
np_3d[[1,2],1:3]

array([[6, 7],
       [4, 5]])

In [65]:
np_3d[1:2,1:3]

array([[6, 7]])

In [66]:
np_2d[2:,1:3]

array([], shape=(0, 2), dtype=int32)

In [68]:
np_4d=np.array([[1,2,3,4],[5,6,7,8],[3,4,5,'8']])

In [69]:
print(np_4d)

[['1' '2' '3' '4']
 ['5' '6' '7' '8']
 ['3' '4' '5' '8']]


In [71]:
print(type(np_4d))

<class 'numpy.ndarray'>


In [72]:
print(np_4d.shape)

(3, 4)


In [73]:
np_4d

array([['1', '2', '3', '4'],
       ['5', '6', '7', '8'],
       ['3', '4', '5', '8']], dtype='<U11')

In [74]:
# normal distribution stack creation
height=np.round(np.random.normal(1.75,0.20,5000),2)
weight=np.round(np.random.normal(60.32,15,5000),2)

In [77]:
print(weight.shape)

(5000,)


In [79]:
np_city=np.column_stack((height,weight))

In [81]:
print(np_city.shape)

(5000, 2)
